# https://codeberg.org/Calamares/calamares/src/branch/calamares/src/modules/mount/mount.conf
extraMounts:
    - device: proc
      fs: proc
      mountPoint: /proc
    - device: sys
      fs: sysfs
      mountPoint: /sys
    - device: /dev
      mountPoint: /dev
      options: [ bind ]
    - device: tmpfs
      fs: tmpfs
      mountPoint: /run
    - device: /run/udev
      mountPoint: /run/udev
      options: [ bind ]
    - device: efivarfs
      fs: efivarfs
      mountPoint: /sys/firmware/efi/efivars
      efi: true

# Garuda's default Btrfs subvolume layout
btrfsSubvolumes:
    - mountPoint: /
      subvolume: /@
    - mountPoint: /home
      subvolume: /@home
    - mountPoint: /root
      subvolume: /@root
    - mountPoint: /srv
      subvolume: /@srv
    - mountPoint: /nix
      subvolume: /@nix
    - mountPoint: /var/cache
      subvolume: /@cache
    - mountPoint: /var/log
      subvolume: /@log
    - mountPoint: /var/tmp
      subvolume: /@tmp

# Mount options by filesystem type
# nixos-generate-config picks these up for hardware-configuration.nix
mountOptions:
    - filesystem: efi
      options: [ fmask=0077, dmask=0077 ]
    - filesystem: btrfs
      options: [ compress=zstd:1, noatime ]
