groupsUrl: local

required: false

label:
    sidebar: "Preset"
    title: "Hardware preset"

groups:
    - name: "Desktop"
      description: "Performance tweaks, no SSH. Best for desktop PCs."
      selected: false
      packages:
        - name: garuda-preset-desktop
          description: "Performance tweaks, no SSH."
    - name: "Laptop"
      description: "Powersave and laptop hardware tweaks. Best for laptops."
      selected: false
      packages:
        - name: garuda-preset-laptop
          description: "Powersave and laptop hardware tweaks."
    - name: "Server"
      description: "Headless setup with SSH and firewall enabled."
      selected: false
      packages:
        - name: garuda-preset-server
          description: "Headless setup with SSH and firewall."
    - name: "Handheld"
      description: "Gaming and performance tweaks. Best for handhelds."
      selected: false
      packages:
        - name: garuda-preset-handheld
          description: "Gaming and performance tweaks."
