---
stages: [update, tag]
variables:
  GIT_AUTHOR_EMAIL: ci@garudalinux.org
  GIT_AUTHOR_NAME: Gitlab CI
  GIT_STRATEGY: clone
update:
  stage: update
  image: nixpkgs/nix-flakes:latest
  script:
    - nix flake update
    - nix flake update --flake ./internal/updater --inputs-from . --override-input nixpkgs "nixpkgs"
    - |
      if git diff --exit-code; then
        echo "No changes to flake.lock"
        exit 0;
      fi
    - |
      git config --global user.name "$GIT_AUTHOR_NAME"
      git config --global user.email "$GIT_AUTHOR_EMAIL"
    - git add flake.lock internal/updater/flake.lock
    - "git commit -m 'chore(flake.lock): bump flakes'"
    - git push "$CI_REPOSITORY_URL" HEAD:main
  only:
    variables: [$UPDATE == "true"]
    refs: [main]
tag:
  stage: tag
  image: nixpkgs/nix-flakes:latest
  script:
    # Test and deploy
    - nix flake check
    - nix build .#internal.ci-bare --dry-run >/dev/null
    - nix build .#internal.ci-full --dry-run >/dev/null
    - git tag -f v2
    - git push --atomic -f $CI_REPOSITORY_URL v2 HEAD:refs/heads/stable
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "merge_request"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "main" && $UPDATE != "true"'
      when: on_success
    - when: never
