---
stages: [update, tag]
variables:
  GIT_AUTHOR_EMAIL: ci@garudalinux.org
  GIT_AUTHOR_NAME: Gitlab CI
  GIT_STRATEGY: clone
  REPO_URL: $CI_SERVER_PROTOCOL://gitlab-ci-token:$ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
update:
  stage: update
  image: nixpkgs/nix-flakes:latest
  script:
    - nix flake update
    - nix flake update ./internal/updater --inputs-from . --override-input nixpkgs "nixpkgs"
    - git config --global user.name "$GIT_AUTHOR_NAME"
    - git config --global user.email "$GIT_AUTHOR_EMAIL"
    - git add flake.lock internal/updater/flake.lock
    - "git commit -m 'chore(flake.lock): bump flakes'"
    - git push "$REPO_URL" HEAD:main
  only:
    variables: [$UPDATE == "true"]
    refs: [main]
tag:
  stage: tag
  image: nixpkgs/nix-flakes:latest
  script:
    # Test and deploy
    - nix flake check
    - nix build .#internal.ci --dry-run
    - git tag -f v2
    - git push --atomic -f $REPO_URL v2 HEAD:refs/heads/stable
  only:
    refs: [main]
    variables: [$UPDATE != "true"]
