"""Render garuda.* NixOS options (nixosOptionsDoc JSON) as Markdown."""

import json
import re
import sys

STORE_PREFIX = re.compile(r"^/nix/store/[^-]+-source/")

def fmt(value):
    if value is None:
        return None
    if isinstance(value, dict):
        # nixosOptionsDoc renders literals as {"_type": ..., "text": ...}
        if "text" in value and isinstance(value["text"], str):
            return value["text"]
        return json.dumps(value)
    return str(value)


def main():
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <nixosOptionsDoc.json>", file=sys.stderr)
        return 1
    with open(sys.argv[1], encoding="utf-8") as f:
        options = json.load(f)

    garuda = sorted(n for n in options if n == "garuda" or n.startswith("garuda."))
    groups = {}
    for name in garuda:
        # Section per subsystem (garuda.<name>), one subsection per option.
        parts = name.split(".")
        section = ".".join(parts[:2]) if len(parts) > 2 else name
        groups.setdefault(section, []).append(name)
    out = [
        "# Garuda module options",
        "",
        "<!-- GENERATED by `gendocs`. Do not edit by hand. -->",
        "",
        f"_{len(garuda)} options under `garuda.*`._",
        "",
    ]
    for section in sorted(groups):
        out.append(f"## `{section}`")
        out.append("")
        for name in groups[section]:
            opt = options[name]
            out.append(f"### `{name}`")
            out.append("")
            if opt.get("description"):
                out.append(opt["description"].strip())
                out.append("")
            details = []
            for key in ("type", "default", "example"):
                rendered = fmt(opt.get(key))
                if rendered:
                    details.append(f"- **{key.capitalize()}**: `{rendered}`")
            if opt.get("declarations"):
                decls = ", ".join(
                    f"`{STORE_PREFIX.sub('', d)}`" for d in opt["declarations"]
                )
                details.append(f"- **Declared in**: {decls}")
            out.extend(details)
            out.append("")
    sys.stdout.write("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
